buildscript {
    ext.kp_version = '1.8.22'
    ext.gp_version = '8.6.1'

    repositories {
        google()
        mavenCentral()
    }

    dependencies {
        classpath "com.android.tools.build:gradle:$gp_version"
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kp_version"
    }
}

plugins {
    id 'org.jetbrains.kotlin.android' version "${kp_version}" apply false
    id 'com.cefrium' apply false
}

tasks.register('clean', Delete) {
    delete rootProject.layout.buildDirectory
}
