pluginManagement {
    includeBuild('build-logic/cefrium-plugin')
    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
    }
}

dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
        maven { url 'https://jcenter.bintray.com/' }
        maven { url 'https://codeberg.org/api/packages/cefrium/maven' } // Warning: this repository is going to shut down soon
        maven {
            url 'https://download.01.org/crosswalk/releases/crosswalk/android/maven2'
        }
    }
}
rootProject.name = "LAMPA"
include ':app'
